-- Create the dimension_rocket table
CREATE TABLE dimension_rocket
(
    id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meters DOUBLE PRECISION,
    feet   DOUBLE PRECISION
);

-- Create the mass_rocket table
CREATE TABLE mass_rocket
(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kg INT,
    lb INT
);

-- Create the thrust_stage table
CREATE TABLE thrust_stage
(
    id  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kn  INT,
    lbf INT
);

-- Create the composite_fairing table
CREATE TABLE composite_fairing
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    height_id   INT,
    diameter_id INT,
    FOREIGN KEY (height_id) REFERENCES dimension_rocket (id),
    FOREIGN KEY (diameter_id) REFERENCES dimension_rocket (id)
);

-- Create the isp table
CREATE TABLE isp
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sea_level INT,
    vacuum    INT
);

-- Create the engines table
CREATE TABLE engines
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number              INT,
    type                VARCHAR(255),
    version             VARCHAR(255),
    layout              VARCHAR(255),
    isp_id              INT,
    engine_loss_max     INT,
    propellant_1        VARCHAR(255),
    propellant_2        VARCHAR(255),
    thrust_sea_level_id INT,
    thrust_vacuum_id    INT,
    thrust_to_weight    INT,
    FOREIGN KEY (isp_id) REFERENCES isp (id),
    FOREIGN KEY (thrust_sea_level_id) REFERENCES thrust_stage (id),
    FOREIGN KEY (thrust_vacuum_id) REFERENCES thrust_stage (id)
);

-- Create the landing_legs table
CREATE TABLE landing_legs
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number   INT,
    material VARCHAR(255)
);

-- Create the first_stage table
CREATE TABLE first_stage
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reusable            BOOLEAN,
    engines             INT,
    fuel_amount_tons    DOUBLE PRECISION,
    burn_time_sec       INT,
    thrust_sea_level_id INT,
    thrust_vacuum_id    INT,
    FOREIGN KEY (thrust_sea_level_id) REFERENCES thrust_stage (id),
    FOREIGN KEY (thrust_vacuum_id) REFERENCES thrust_stage (id)
);

-- Create the payloads table
CREATE TABLE payloads
(
    id                   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    option_1             VARCHAR(255),
    option_2             VARCHAR(255),
    composite_fairing_id INT,
    FOREIGN KEY (composite_fairing_id) REFERENCES composite_fairing (id)
);

-- Create the second_stage table
CREATE TABLE second_stage
(
    id               INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    engines          INT,
    fuel_amount_tons DOUBLE PRECISION,
    burn_time_sec    INT,
    thrust_id        INT,
    payloads_id      INT,
    FOREIGN KEY (thrust_id) REFERENCES thrust_stage (id),
    FOREIGN KEY (payloads_id) REFERENCES payloads (id)
);

-- Create the rocket table
CREATE TABLE rocket
(
    id               INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    active           BOOLEAN,
    stages           INT,
    boosters         INT,
    cost_per_launch  INT,
    success_rate_pct INT,
    first_flight     VARCHAR(255),
    country          VARCHAR(255),
    company          VARCHAR(255),
    height_id        INT,
    diameter_id      INT,
    mass_id          INT,
    first_stage_id   INT,
    second_stage_id  INT,
    engines_id       INT,
    landing_legs_id  INT,
    wikipedia        TEXT,
    description      TEXT,
    rocket_id        VARCHAR(255),
    rocket_name      VARCHAR(255),
    rocket_type      VARCHAR(255),
    FOREIGN KEY (height_id) REFERENCES dimension_rocket (id),
    FOREIGN KEY (diameter_id) REFERENCES dimension_rocket (id),
    FOREIGN KEY (mass_id) REFERENCES mass_rocket (id),
    FOREIGN KEY (first_stage_id) REFERENCES first_stage (id),
    FOREIGN KEY (second_stage_id) REFERENCES second_stage (id),
    FOREIGN KEY (engines_id) REFERENCES engines (id),
    FOREIGN KEY (landing_legs_id) REFERENCES landing_legs (id)
);

-- Create the payload_weights table
CREATE TABLE payload_weights
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payload_id VARCHAR(255),
    name       VARCHAR(255),
    kg         INT,
    lb         INT,
    rocket_id  INT,
    FOREIGN KEY (rocket_id) REFERENCES rocket (id)
);

-- Create the flickr_images table
CREATE TABLE flickr_images
(
    rocket_id INT,
    url VARCHAR(255),
    FOREIGN KEY (rocket_id) REFERENCES rocket(id)
);
