-- Create the sx_dimension_rocket table
CREATE TABLE sx_dimension_rocket
(
    id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meters DOUBLE PRECISION,
    feet   DOUBLE PRECISION
);

-- Create the sx_mass_rocket table
CREATE TABLE sx_mass_rocket
(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kg INT,
    lb INT
);

-- Create the sx_thrust_stage table
CREATE TABLE sx_thrust_stage
(
    id  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kn  INT,
    lbf INT
);

-- Create the sx_composite_fairing table
CREATE TABLE sx_composite_fairing
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    height_id   INT,
    diameter_id INT,
    FOREIGN KEY (height_id) REFERENCES sx_dimension_rocket (id),
    FOREIGN KEY (diameter_id) REFERENCES sx_dimension_rocket (id)
);

-- Create the sx_isp table
CREATE TABLE sx_isp
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sea_level INT,
    vacuum    INT
);

-- Create the sx_engines table
CREATE TABLE sx_engines
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number              INT,
    type                VARCHAR(255),
    version             VARCHAR(255),
    layout              VARCHAR(255),
    isp_id              INT,
    engine_loss_max     INT,
    propellant_1        VARCHAR(255),
    propellant_2        VARCHAR(255),
    thrust_sea_level_id INT,
    thrust_vacuum_id    INT,
    thrust_to_weight    INT,
    FOREIGN KEY (isp_id) REFERENCES sx_isp (id),
    FOREIGN KEY (thrust_sea_level_id) REFERENCES sx_thrust_stage (id),
    FOREIGN KEY (thrust_vacuum_id) REFERENCES sx_thrust_stage (id)
);

-- Create the sx_landing_legs table
CREATE TABLE sx_landing_legs
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number   INT,
    material VARCHAR(255)
);

-- Create the sx_first_stage table
CREATE TABLE sx_first_stage
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reusable            BOOLEAN,
    engines             INT,
    fuel_amount_tons    DOUBLE PRECISION,
    burn_time_sec       INT,
    thrust_sea_level_id INT,
    thrust_vacuum_id    INT,
    FOREIGN KEY (thrust_sea_level_id) REFERENCES sx_thrust_stage (id),
    FOREIGN KEY (thrust_vacuum_id) REFERENCES sx_thrust_stage (id)
);

-- Create the sx_payloads table
CREATE TABLE sx_payloads
(
    id                   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    option_1             VARCHAR(255),
    option_2             VARCHAR(255),
    composite_fairing_id INT,
    FOREIGN KEY (composite_fairing_id) REFERENCES sx_composite_fairing (id)
);

-- Create the sx_second_stage table
CREATE TABLE sx_second_stage
(
    id               INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    engines          INT,
    fuel_amount_tons DOUBLE PRECISION,
    burn_time_sec    INT,
    thrust_id        INT,
    payloads_id      INT,
    FOREIGN KEY (thrust_id) REFERENCES sx_thrust_stage (id),
    FOREIGN KEY (payloads_id) REFERENCES sx_payloads (id)
);

-- Create the sx_rocket table
CREATE TABLE sx_rocket
(
    id               INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    active           BOOLEAN,
    stages           INT,
    boosters         INT,
    cost_per_launch  INT,
    success_rate_pct INT,
    first_flight     VARCHAR(255),
    country          VARCHAR(255),
    company          VARCHAR(255),
    height_id        INT,
    diameter_id      INT,
    mass_id          INT,
    first_stage_id   INT,
    second_stage_id  INT,
    engines_id       INT,
    landing_legs_id  INT,
    wikipedia        VARCHAR(255),
    description      TEXT,
    rocket_id        VARCHAR(255),
    rocket_name      VARCHAR(255),
    rocket_type      VARCHAR(255),
    FOREIGN KEY (height_id) REFERENCES sx_dimension_rocket (id),
    FOREIGN KEY (diameter_id) REFERENCES sx_dimension_rocket (id),
    FOREIGN KEY (mass_id) REFERENCES sx_mass_rocket (id),
    FOREIGN KEY (first_stage_id) REFERENCES sx_first_stage (id),
    FOREIGN KEY (second_stage_id) REFERENCES sx_second_stage (id),
    FOREIGN KEY (engines_id) REFERENCES sx_engines (id),
    FOREIGN KEY (landing_legs_id) REFERENCES sx_landing_legs (id)
);

-- Create the sx_payload_weights table
CREATE TABLE sx_payload_weights
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rocket_id  INT,
    payload_id VARCHAR(255),
    name       VARCHAR(255),
    kg         INT,
    lb         INT,
    FOREIGN KEY (rocket_id) REFERENCES sx_rocket (id)
);

-- Create the sx_image_url table
CREATE TABLE sx_image_url
(
    id  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url VARCHAR(255)
);

-- Create the sx_flickr_images table
CREATE TABLE sx_flickr_images
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rocket_id INT,
    url_id    INT,
    FOREIGN KEY (rocket_id) REFERENCES sx_rocket (id),
    FOREIGN KEY (url_id) REFERENCES sx_image_url (id)
);
